export type SFW =
    | "awoo"
    | "bite"
    | "blush"
    | "bonk"
    | "bully"
    | "cringe"
    | "cry"
    | "cuddle"
    | "dance"
    | "glomp"
    | "handhold"
    | "happy"
    | "highfive"
    | "hug"
    | "kick"
    | "kill"
    | "kiss"
    | "lick"
    | "megumin"
    | "neko"
    | "nom"
    | "pat"
    | "poke"
    | "shinobu"
    | "slap"
    | "smile"
    | "smug"
    | "waifu"
    | "wave"
    | "wink"
    | "yeet"

export type NSFW = "blowjob" | "neko" | "trap" | "waifu"

export type Endpoints = SFW | NSFW
